# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
 
    - name: Public IP
      id: ip
      uses: haythem/public-ip@v1.2
      
    - name: Setup Google Cloud SDK
      uses: mathrix-education/setup-gcloud@1.2.2
      with:
        service-account-key:  ${{ secrets.GKE_SA_KEY }}
        project: ${{ secrets.GKE_PROJECT }}

    - name: Set Ips
      run: gcloud sql instances patch postgre-psi --authorized-networks=${{ steps.ip.outputs.ipv4 }},189.120.79.60,34.73.241.32,35.185.59.139,104.196.12.141,201.68.207.176,187.38.232.140,201.26.155.25,200.171.47.6,200.161.102.129,35.237.152.39,35.185.59.139,35.243.161.61,34.75.212.245,35.190.167.205,34.75.149.158

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Set Ips remove
      run: gcloud sql instances patch postgre-psi --authorized-networks=189.120.79.60,34.73.241.32,35.185.59.139,104.196.12.141,201.68.207.176,187.38.232.140,201.26.155.25,200.171.47.6,200.161.102.129,35.237.152.39,35.185.59.139,35.243.161.61,34.75.212.245,35.190.167.205,34.75.149.158
